# Generated by Django 3.1 on 2020-09-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeePortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
