# Generated by Django 3.1 on 2020-09-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeePortal', '0003_auto_20200920_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpName', models.CharField(max_length=500)),
                ('EmpID', models.CharField(max_length=10)),
                ('Designation', models.CharField(max_length=200)),
                ('CurrentlyEmployed', models.BooleanField(default=True)),
                ('Mobile', models.CharField(max_length=12)),
                ('PersonalEmail', models.EmailField(blank=True, max_length=254)),
                ('OfficialEmail', models.EmailField(blank=True, max_length=254)),
                ('StartDate', models.DateField()),
            ],
        ),
    ]
