# Generated by Django 3.1 on 2020-09-20 09:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employeePortal', '0005_auto_20200920_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True)),
                ('Description', models.TextField(max_length=3000)),
            ],
        ),
        migrations.RemoveField(
            model_name='timesheets',
            name='Date',
        ),
        migrations.AddField(
            model_name='timesheets',
            name='Day1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='Day2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='Day3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='Day4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='Day5',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='Day6',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='Day7',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='EndPeriod',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='Notes',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='ProjectName',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='employeePortal.projects', verbose_name='Select Project'),
        ),
        migrations.AddField(
            model_name='timesheets',
            name='StartPeriod',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
