# Generated by Django 3.1 on 2020-09-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeePortal', '0007_auto_20200920_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='EndDate',
            field=models.DateField(blank=True, default=None),
        ),
    ]
