# Generated by Django 3.1 on 2020-10-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeePortal', '0008_auto_20200920_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True)),
                ('Description', models.TextField(max_length=3000)),
            ],
        ),
        migrations.DeleteModel(
            name='Days',
        ),
    ]
