# Generated by Django 3.1 on 2020-10-04 10:07

from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('employeePortal', '0009_auto_20201001_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheetMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpUser', models.CharField(default=django_currentuser.middleware.get_current_authenticated_user, editable=None, max_length=100)),
                ('title', models.CharField(max_length=1024)),
                ('slug', models.SlugField(max_length=1024)),
                ('ProjectName', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='employeePortal.projects', verbose_name='Select Project')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheetDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='employeePortal.timesheetmain')),
            ],
        ),
    ]
