# Generated by Django 3.1 on 2020-10-17 04:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employeePortal', '0011_auto_20201004_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetmain',
            name='ProjectName',
        ),
        migrations.AddField(
            model_name='timesheetdate',
            name='ProjectName',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='employeePortal.projects', verbose_name='Select Project'),
        ),
        migrations.AddField(
            model_name='timesheetmain',
            name='SubmitDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timesheetdate',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
