# Generated by Django 3.1 on 2020-10-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeePortal', '0012_auto_20201016_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='EndDate',
            field=models.DateField(blank=True),
        ),
    ]
