# Generated by Django 3.1 on 2020-10-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeePortal', '0013_auto_20201016_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='employees',
            name='Education',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employees',
            name='Experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='SkillSet',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='employees',
            name='EndDate',
            field=models.DateField(blank=True, default='1989-01-01'),
        ),
    ]
