# Generated by Django 3.1 on 2020-08-23 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200822_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoty_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.procategory', verbose_name='name'),
        ),
    ]
