# Generated by Django 3.1 on 2020-08-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200823_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Image3',
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.CharField(choices=[('1', 'Bangles'), ('2', 'Bracelet'), ('3', 'Chains'), ('4', 'Ring'), ('5', 'Earring'), ('6', 'Mangalsutra'), ('7', 'Necklace'), ('8', 'Nosepin'), ('9', 'Pendant'), ('10', 'General')], default='Select Category', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('1', 'Kids'), ('2', 'Men'), ('3', 'Women'), ('4', 'Unisex')], default='Select Gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=2083),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True),
        ),
    ]
