# Generated by Django 3.1 on 2020-10-03 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_show_showphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('1', 'Kids'), ('2', 'Men'), ('3', 'Women'), ('4', 'Unisex')], default='Select Gender', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SampleMultipleImgProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='products.productmain')),
            ],
        ),
    ]
