# Generated by Django 3.1 on 2020-10-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201004_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmain',
            name='categoty_id',
        ),
    ]
