# Generated by Django 3.1 on 2020-10-04 06:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_productmain_categoty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmain',
            name='addedOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productmain',
            name='categoty_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.procategory', verbose_name='Category Name'),
        ),
    ]
