# Generated by Django 3.1 on 2020-10-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20201004_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmain',
            old_name='categoty_id',
            new_name='categoryName',
        ),
    ]
