# Generated by Django 3.1 on 2020-10-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20201004_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showphoto',
            name='show',
        ),
        migrations.DeleteModel(
            name='Show',
        ),
        migrations.DeleteModel(
            name='ShowPhoto',
        ),
    ]
